INSERT INTO `USER` (NAME, `DATE`, `STATUS`, `TYPE`, `VERSION`) VALUES('BANK', CURRENT_TIMESTAMP, 'ACTIVE', 'BUSINESS', 1);

INSERT INTO `ACCOUNT` (USER_ID, `TYPE`, `VERSION`, `STATUS`, `DATE`) VALUES(1, "CHECKING", 0, "ACTIVE", CURRENT_TIMESTAMP);