CREATE TABLE IF NOT EXISTS `USER` (
	ID INT auto_increment NOT NULL,
	FIRST_NAME varchar(100) NOT NULL,
	MIDDLE_NAME varchar(100) NULL,
	LAST_NAME varchar(100) NOT NULL,
	`TYPE` varchar(100) NOT NULL,
	STATUS varchar(100) NOT NULL,
	VERSION INT NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT USER_pk PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;
