CREATE TABLE IF NOT EXISTS `USER` (
	ID BIGINT auto_increment NOT NULL,
	NAME varchar(100) NOT NULL,
	`TYPE` varchar(100) NOT NULL,
	`VERSION` INT NOT NULL,
	`STATUS` varchar(100) NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT USER_pk PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;