CREATE TABLE IF NOT EXISTS `ACCOUNT` (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	USER_ID BIGINT NOT NULL,
	`TYPE` VARCHAR(100) NOT NULL,
	`VERSION` INT NOT NULL,
	`STATUS` VARCHAR(100) NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT account_pk PRIMARY KEY (ID),
	CONSTRAINT account_FK FOREIGN KEY (USER_ID) REFERENCES `USER`(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;

INSERT INTO `ACCOUNT`
(USER_ID, `TYPE`, `VERSION`, `STATUS`, `DATE`)
VALUES(1, "CHECKING", 0, "ACTIVE", CURRENT_TIMESTAMP);