CREATE TABLE IF NOT EXISTS ACCOUNT (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	USERID BIGINT NOT NULL,
	`TYPE` VARCHAR(100) NOT NULL,
	`VERSION` INT NOT NULL,
	`STATUS` VARCHAR(100) NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT account_pk PRIMARY KEY (ID),
	CONSTRAINT account_FK FOREIGN KEY (UserID) REFERENCES `USER`(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;
