CREATE TABLE IF NOT EXISTS account (
	ID BIGINT auto_increment NOT NULL,
	UserID BIGINT NOT NULL,
	`Type` varchar(100) NOT NULL,
	Version INT NOT NULL,
	Status varchar(100) NOT NULL,
	`Date` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT account_pk PRIMARY KEY (ID),
	CONSTRAINT account_FK FOREIGN KEY (UserID) REFERENCES `USER`(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;
