CREATE TABLE IF NOT EXISTS `TRANSACTION` (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	FROM_ACCOUNT_ID BIGINT NULL,
	TO_ACCOUNT_ID BIGINT NULL,
	`TYPE` VARCHAR(100) NOT NULL,
	`VALUE` FLOAT NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT transaction_pk PRIMARY KEY (ID),
	CONSTRAINT from_FK FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNT(ID),
	CONSTRAINT to_FK FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNT(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;
