CREATE TABLE IF NOT EXISTS `TRANSACTION` (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	FROM_ACCOUNT BIGINT NULL,
	TO_ACCOUNT BIGINT NULL,
	`TYPE` VARCHAR(100) NULL,
	`VALUE` FLOAT NOT NULL,
	`DATE` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT transaction_pk PRIMARY KEY (ID),
	CONSTRAINT from_FK FOREIGN KEY (From_Account) REFERENCES ACCOUNT(ID),
	CONSTRAINT to_FK FOREIGN KEY (To_Account) REFERENCES ACCOUNT(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=ascii
COLLATE=ascii_bin;
